#!/usr/bin/env python3
"""Remove build_graphs output files from a single config/run folder."""

import argparse
from pathlib import Path


def remove_file(path: Path, dry_run: bool) -> bool:
    if not path.exists():
        print(f"skipped (not found): {path.name}")
        return False

    if dry_run:
        print(f"would remove: {path.name}")
        return True

    path.unlink()
    print(f"removed: {path.name}")
    return True


def get_run_folders(folder: Path) -> list[Path]:
    if any(child.is_dir() and child.name.startswith("run_") for child in folder.iterdir() if child.is_dir()):
        return sorted([child for child in folder.iterdir() if child.is_dir() and child.name.startswith("run_")])
    return [folder]


def remove_outputs_in_folder(folder: Path, filenames: list[str], dry_run: bool) -> bool:
    print(f"Processing: {folder}")
    removed_any = False
    for filename in filenames:
        removed_any = remove_file(folder / filename, dry_run) or removed_any
    return removed_any


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Delete PNG graphs and performance_summary.csv generated by build_graphs.py from a config folder or a single run folder."
    )
    parser.add_argument(
        "config_folder",
        help="Path to the config folder containing run_* subfolders, or a single run folder",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show which files would be deleted without removing them",
    )

    args = parser.parse_args()
    folder = Path(args.config_folder)

    if not folder.exists():
        raise SystemExit(f"Error: folder does not exist: {folder}")
    if not folder.is_dir():
        raise SystemExit(f"Error: path is not a directory: {folder}")

    filenames = [
        "01_source_throughput.png",
        "02_global_efficiency.png",
        "03_performance_boxplots.png",
        "performance_summary.csv",
    ]

    print(f"Cleaning build_graphs outputs in: {folder}")
    if args.dry_run:
        print("Dry run enabled. No files will be deleted.")

    run_folders = get_run_folders(folder)
    if len(run_folders) > 1 or run_folders[0] != folder:
        print(f"Found {len(run_folders)} run folder(s) to clean.")

    deleted_any = False
    for run_folder in run_folders:
        deleted_any = remove_outputs_in_folder(run_folder, filenames, args.dry_run) or deleted_any

    if not deleted_any:
        print("No build_graphs output files were found to remove.")
    elif args.dry_run:
        print("Dry run complete.")
    else:
        print("Cleanup complete.")


if __name__ == "__main__":
    main()
